CREATE DATABASE ballot CHARACTER SET 'utf8';


CREATE TABLE elector (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
lastname VARCHAR(20) NOT NULL,
firstname VARCHAR(20) NOT NULL,
code INT(4) NOT NULL,
vote CHAR(3) DEFAULT 'NON' NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB;


CREATE TABLE cp (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
lastname VARCHAR(20) NOT NULL,
firstname VARCHAR(20) NOT NULL ,
image VARCHAR(255) NOT NULL,
voice INT(4) DEFAULT 0 NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB;


CREATE TABLE cpa (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
lastname VARCHAR(20) NOT NULL,
firstname VARCHAR(20) NOT NULL ,
image VARCHAR(255) NOT NULL,
voice INT(4) DEFAULT 0 NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB;


CREATE TABLE Resultat_CP (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
CODE INT(4) NOT NULL,
ID_CP SMALLINT NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB;

CREATE TABLE Resultat_CPA (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
CODE INT(4) NOT NULL,
ID_CPA SMALLINT NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB;


INSERT INTO elector (name, lastname, firstname, code)
VALUES ('KABONGO', 'BILONDA', 'KELLY', '1100'),
('KABONGO', 'MUKENA', 'DIEUDO', '2018'),
('MPOYI', 'MUKENA', 'NATHAN', '1998'),
('MUKENA', 'BAKINA', 'ARSENE', '1122'),
('MPUNGA', 'MUKENA', 'JOEL', '2248'),
('NTUMBA', 'MUKENA', 'SAMUEL', '2998'),
('KAZUMBA', 'KAMPIAMBA', 'BENI', '1198'),
('TSITA', 'POBA', 'JOE', '1908'),
('MBUYAMBA', 'KABUYI', 'MARDOCHEE', '1008'),
('MUTUMBIKA', 'MUKENA', 'CHRISTINE', '1458');





INSERT INTO cp (name, lastname, firstname, image)
VALUES ('KALOMBO', 'MUKENA', 'BENJAMIN', 'templates\\images\\ben.jpg'),
('TSHIMAKINDA', 'MUKENA', 'JOSEPH', 'templates\\images\\joseph.jpg'),
('MUKADI', 'MUKENA', 'JOE', 'templates\\images\\joe.png');


INSERT INTO cpa (name, lastname, firstname, image)
VALUES ('MUTUMBIKA', 'MUKENA', 'CHRISTINE', 'templates\\images\\christine.jpg'),
('MUANDA', 'MBADU', 'YORGHEN', 'templates\\images\\yorghen.jpg'),
('MUSHENDU', 'MUSHENDU', 'WILFRIED', 'templates\\images\\wilfried.png');


